export const ACTION = {
    ADD_EXERCISE: "ADD_EXERCISE",
    REMOVE_EXERCISE: "REMOVE_EXERCISE",
    TOGGLE_EXERCISE: "TOGGLE_EXERCISE",
    HIDE_EXERCISE: "HIDE_EXERCISE",
    SET_TEXT_FILTER: "SET_TEXT_FILTER",
    HIDE_MODAL: "HIDE_MODAL",
    SHOW_MODAL: "SHOW_MODAL",
};

export const MODAL_TYPE = {
    EXERCISE_MODAL: "ExerciseModal",
    EXERCISE_LIST: "ExerciseList",
    HIDDEN: "Hidden",
};
